# TODO: review all rules available and add/remove/reorganize rules to match w/ the doc

env:
  browser: true
  commonjs: true
  es6: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
globals:
  log: true
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    impliedStrict: true
    jsx: true
  ecmaVersion: 2017
  sourceType: module
plugins:
  - jsx-a11y
rules:
  array-bracket-spacing: warn
  arrow-spacing: warn
  block-spacing: warn
  brace-style:
    - warn
    - stroustrup
    - allowSingleLine: true
  comma-dangle:
    - warn
    - only-multiline
  comma-spacing: warn
  computed-property-spacing: warn
  eqeqeq:
    - warn
    - smart
  func-call-spacing: warn
  indent:
    - warn
    - 2
    - SwitchCase: 1
      VariableDeclarator:
        var: 2
        let: 2
        const: 3
  jsx-quotes:
    - warn
    - prefer-double
  key-spacing: warn
  keyword-spacing: warn
  # linebreak-style:
  #   - warn
  #   - unix
  max-len:
    - warn
    - code: 220
      tabWidth: 2
  new-parens: warn
  no-console: off
  no-debugger: warn
  no-extra-semi: warn
  no-empty: warn
  no-multi-spaces: warn
  # no-trailing-spaces: warn
  no-unused-vars: warn
  no-whitespace-before-property: warn
  no-var: warn
  object-curly-spacing:
    - warn
    - always
  # quotes:
  #   - warn
  #   # - single
  #   - avoidEscape: false
  #     allowTemplateLiterals: true
  react/display-name: warn
  react/jsx-curly-spacing:
    - warn
    - when: never
  react/jsx-curly-brace-presence: warn
  react/jsx-tag-spacing:
    - warn
    - beforeClosing: never
  react/no-danger: warn
  react/prop-types: false
  rest-spread-spacing: warn
  semi:
    - warn
    - always
    - omitLastInOneLineBlock: true
  semi-spacing: warn
  space-before-blocks: warn
  space-before-function-paren:
    - warn
    - named: never
      anonymous: never
      asyncArrow: always
  space-in-parens: warn
  space-infix-ops: warn
  space-unary-ops: warn
  # spaced-comment: warn
  switch-colon-spacing: warn
  template-curly-spacing: warn
  template-tag-spacing: warn
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/no-noninteractive-element-to-interactive-role: off
  jsx-a11y/interactive-supports-focus: off
